# Form implementation generated from reading ui file 'D:\My Documents\Work\Frelancing\Projects\Project-time-tracker\gui\ui_files\mod_log_window.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ModifyLogWindow(object):
    def setupUi(self, ModifyLogWindow):
        ModifyLogWindow.setObjectName("ModifyLogWindow")
        ModifyLogWindow.resize(322, 173)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=ModifyLogWindow)
        self.buttonBox.setGeometry(QtCore.QRect(140, 120, 161, 41))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.layoutWidget = QtWidgets.QWidget(parent=ModifyLogWindow)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 70, 281, 26))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.timeEdit_clock_out = QtWidgets.QTimeEdit(parent=self.layoutWidget)
        self.timeEdit_clock_out.setObjectName("timeEdit_clock_out")
        self.horizontalLayout_2.addWidget(self.timeEdit_clock_out)
        self.dateEdit_clock_out = QtWidgets.QDateEdit(parent=self.layoutWidget)
        self.dateEdit_clock_out.setObjectName("dateEdit_clock_out")
        self.horizontalLayout_2.addWidget(self.dateEdit_clock_out)
        self.pushButton_calendar_clock_out = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.pushButton_calendar_clock_out.setObjectName("pushButton_calendar_clock_out")
        self.horizontalLayout_2.addWidget(self.pushButton_calendar_clock_out)
        self.layoutWidget1 = QtWidgets.QWidget(parent=ModifyLogWindow)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 20, 281, 26))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(parent=self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.timeEdit_clock_in = QtWidgets.QTimeEdit(parent=self.layoutWidget1)
        self.timeEdit_clock_in.setObjectName("timeEdit_clock_in")
        self.horizontalLayout.addWidget(self.timeEdit_clock_in)
        self.dateEdit_clock_in = QtWidgets.QDateEdit(parent=self.layoutWidget1)
        self.dateEdit_clock_in.setObjectName("dateEdit_clock_in")
        self.horizontalLayout.addWidget(self.dateEdit_clock_in)
        self.pushButton_calendar_clock_in = QtWidgets.QPushButton(parent=self.layoutWidget1)
        self.pushButton_calendar_clock_in.setObjectName("pushButton_calendar_clock_in")
        self.horizontalLayout.addWidget(self.pushButton_calendar_clock_in)

        self.retranslateUi(ModifyLogWindow)
        self.buttonBox.accepted.connect(ModifyLogWindow.accept) # type: ignore
        self.buttonBox.rejected.connect(ModifyLogWindow.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ModifyLogWindow)

    def retranslateUi(self, ModifyLogWindow):
        _translate = QtCore.QCoreApplication.translate
        ModifyLogWindow.setWindowTitle(_translate("ModifyLogWindow", "Dialog"))
        self.label_3.setText(_translate("ModifyLogWindow", "Clock-out"))
        self.pushButton_calendar_clock_out.setText(_translate("ModifyLogWindow", "Select"))
        self.label_2.setText(_translate("ModifyLogWindow", "Clock-in"))
        self.pushButton_calendar_clock_in.setText(_translate("ModifyLogWindow", "Select"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ModifyLogWindow = QtWidgets.QDialog()
    ui = Ui_ModifyLogWindow()
    ui.setupUi(ModifyLogWindow)
    ModifyLogWindow.show()
    sys.exit(app.exec())
