# Form implementation generated from reading ui file 'D:\My Documents\Work\Frelancing\Projects\Project-time-tracker\gui\ui_files\select_log_window.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SelectLogWindow(object):
    def setupUi(self, SelectLogWindow):
        SelectLogWindow.setObjectName("SelectLogWindow")
        SelectLogWindow.resize(488, 300)
        self.tableWidget_log_edit = QtWidgets.QTableWidget(parent=SelectLogWindow)
        self.tableWidget_log_edit.setGeometry(QtCore.QRect(10, 50, 471, 211))
        self.tableWidget_log_edit.setObjectName("tableWidget_log_edit")
        self.tableWidget_log_edit.setColumnCount(0)
        self.tableWidget_log_edit.setRowCount(0)
        self.comboBox_projects = QtWidgets.QComboBox(parent=SelectLogWindow)
        self.comboBox_projects.setGeometry(QtCore.QRect(60, 20, 151, 22))
        self.comboBox_projects.setObjectName("comboBox_projects")
        self.label_2 = QtWidgets.QLabel(parent=SelectLogWindow)
        self.label_2.setGeometry(QtCore.QRect(10, 20, 43, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.widget = QtWidgets.QWidget(parent=SelectLogWindow)
        self.widget.setGeometry(QtCore.QRect(320, 270, 161, 26))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_edit_log = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton_edit_log.setObjectName("pushButton_edit_log")
        self.horizontalLayout.addWidget(self.pushButton_edit_log)
        self.pushButton_delete_log = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton_delete_log.setObjectName("pushButton_delete_log")
        self.horizontalLayout.addWidget(self.pushButton_delete_log)

        self.retranslateUi(SelectLogWindow)
        QtCore.QMetaObject.connectSlotsByName(SelectLogWindow)

    def retranslateUi(self, SelectLogWindow):
        _translate = QtCore.QCoreApplication.translate
        SelectLogWindow.setWindowTitle(_translate("SelectLogWindow", "Dialog"))
        self.label_2.setText(_translate("SelectLogWindow", "Project:"))
        self.pushButton_edit_log.setText(_translate("SelectLogWindow", "Edit"))
        self.pushButton_delete_log.setText(_translate("SelectLogWindow", "Delete"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SelectLogWindow = QtWidgets.QDialog()
    ui = Ui_SelectLogWindow()
    ui.setupUi(SelectLogWindow)
    SelectLogWindow.show()
    sys.exit(app.exec())
