# Form implementation generated from reading ui file '.\main_window.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(423, 369)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_print_out = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_print_out.setGeometry(QtCore.QRect(10, 90, 401, 231))
        self.label_print_out.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_print_out.setText("")
        self.label_print_out.setObjectName("label_print_out")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 50, 401, 26))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.button_clock_in = QtWidgets.QPushButton(parent=self.widget)
        self.button_clock_in.setObjectName("button_clock_in")
        self.horizontalLayout.addWidget(self.button_clock_in)
        self.button_clock_out = QtWidgets.QPushButton(parent=self.widget)
        self.button_clock_out.setObjectName("button_clock_out")
        self.horizontalLayout.addWidget(self.button_clock_out)
        self.button_sessions = QtWidgets.QPushButton(parent=self.widget)
        self.button_sessions.setObjectName("button_sessions")
        self.horizontalLayout.addWidget(self.button_sessions)
        self.button_report = QtWidgets.QPushButton(parent=self.widget)
        self.button_report.setObjectName("button_report")
        self.horizontalLayout.addWidget(self.button_report)
        self.button_status = QtWidgets.QPushButton(parent=self.widget)
        self.button_status.setObjectName("button_status")
        self.horizontalLayout.addWidget(self.button_status)
        self.widget1 = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(20, 10, 391, 24))
        self.widget1.setObjectName("widget1")
        self.formLayout = QtWidgets.QFormLayout(self.widget1)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(parent=self.widget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_2)
        self.line_edit_project = QtWidgets.QLineEdit(parent=self.widget1)
        self.line_edit_project.setObjectName("line_edit_project")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.line_edit_project)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 423, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.button_clock_in.setText(_translate("MainWindow", "Clock-in"))
        self.button_clock_out.setText(_translate("MainWindow", "Clock-out"))
        self.button_sessions.setText(_translate("MainWindow", "Sessions"))
        self.button_report.setText(_translate("MainWindow", "Report"))
        self.button_status.setText(_translate("MainWindow", "Status"))
        self.label_2.setText(_translate("MainWindow", "PROJECT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
